server:
  address: ":1337"
  storage_path: "./storage"
 #Ограничения по работе с файлами по ТЗ:
  limits:
    upload: 10  #10 запросов на загрузку
    download: 10 #10 запросов на скачивание
    list: 100 #100 запросов на просмотр

client:
  server_address: "localhost:1488"